name: Helm chart image tag check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download "helm-chart-update-check"
        uses: engineerd/configurator@v0.0.10
        with:
          name: "hcuc"
          fromGitHubReleases: "true"
          repo: "pmoscode/helm-chart-update-check"
          urlTemplate: "https://github.com/pmoscode/helm-chart-update-check/releases/download/{{version}}/hcuc-{{version}}-linux-amd64.tar.gz"
          version: "v0.1.0"
          pathInArchive: "hcuc"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for updates
        run: |
          hcuc --docker-hub-repo gotify/server --debug
